name: Verbose Curl Request Workflow

on:
  push:
    branches:
      - master

jobs:
  verbose_curl_request_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make verbose curl request and print detailed response
        run: |
          echo "Starting curl request to the endpoint..."
          response=$(curl -v -w "\nHTTP Status: %{http_code}\n" -o response_body.txt https://www.google.com/endpoint 2>&1)
          echo "Curl command output:"
          echo "$response"
          echo "Response Body:"
          cat response_body.txt
          echo "Curl request completed."
